server:
  port: 8300   # 设置服务器端口
  servlet:
    context-path: /sport  # 设置应用的上下文路径
spring:
  profiles:
    active: dev
logging:
  level:
    root: INFO  # 设置根日志级别
    org.springframework.web.client.RestTemplate: DEBUG
    org.springframework.http: DEBUG

